/* eslint-disable */
// Generated by component library do not modify
import ButtonButton from './Button/Button.js';
import HeaderHeader from './Header/Header.js';
import InputInput from './Input/Input.js';
import LoaderLoader from './Loader/Loader.js';

function dispatchEvent(data) {
  if (typeof window !== 'undefined') {
    const BluekitEvent = require('react-bluekit/lib/libraries/BluekitEvent');
    document.dispatchEvent(new BluekitEvent('functionTriggered', data));
  } else
    console.log('Bluekit received function triggered', data)
}

export default {
  ButtonButton: {
    name: 'ButtonButton',
    menu: 'Button Button',
    file: './Button/Button.js',
    component: ButtonButton,
    componentName: 'Button',
    description: '',
    customProps: {},
    propsDefinition: {backgroundColor:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#3498db'",computed:false}},color:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#fff'",computed:false}},children:{type:{name:"any"},required:false,description:""}},
    simpleProps: {backgroundColor:"#3498db",color:"#fff"},
    fullProps: {type:"dupa",backgroundColor:"#3498db",color:"#fff",children:"ANY children"}
  },
  HeaderHeader: {
    name: 'HeaderHeader',
    menu: 'Header Header',
    file: './Header/Header.js',
    component: HeaderHeader,
    componentName: 'Header',
    description: '',
    customProps: {},
    propsDefinition: {backgroundColor:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#3498db'",computed:false}},color:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#fff'",computed:false}},children:{type:{name:"any"},required:false,description:""}},
    simpleProps: {backgroundColor:"#3498db",color:"#fff"},
    fullProps: {backgroundColor:"#3498db",color:"#fff",children:"ANY children"}
  },
  InputInput: {
    name: 'InputInput',
    menu: 'Input Input',
    file: './Input/Input.js',
    component: InputInput,
    componentName: 'Input',
    description: '',
    customProps: {},
    propsDefinition: {backgroundColor:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#fff'",computed:false}},color:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#bdc3c7'",computed:false}}},
    simpleProps: {backgroundColor:"#fff",color:"#bdc3c7"},
    fullProps: {backgroundColor:"#fff",color:"#bdc3c7"}
  },
  LoaderLoader: {
    name: 'LoaderLoader',
    menu: 'Loader Loader',
    file: './Loader/Loader.js',
    component: LoaderLoader,
    componentName: 'Loader',
    description: '',
    customProps: {},
    propsDefinition: {background:{type:{name:"string"},required:false,description:"",defaultValue:{value:"'#fff'",computed:false}},color:{type:{name:"enum",value:[{value:"'#3498db'",computed:false},{value:"'#2ecc71'",computed:false},{value:"'#e74c3c'",computed:false}]},required:false,description:"",defaultValue:{value:"'#3498db'",computed:false}},duration:{type:{name:"number"},required:false,description:"",defaultValue:{value:"1.4",computed:false}},size:{type:{name:"number"},required:false,description:"",defaultValue:{value:"6",computed:false}}},
    simpleProps: {background:"pink",color:"#3498db",duration:1.4,size:6},
    fullProps: {background:"#fff",color:"#3498db",duration:1.4,size:6}
  },
}
